version: "3.9"
services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - frontend:/app
    ports:
      - "3000:3000"
    restart: always
  backend:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: kpgts
      SESSION_SECRET: "ini secret"
      IMAGE_FOLDER: "uploads"
      MAILER_FROM: noreply@kpgts2022.com
      MAILER_HOST: localhost
      MAILER_PORT: 25
      MAILER_USERNAME: ""
      MAILER_PASSWORD: ""
      ORIGIN_URL: "backend:3001"
      OPREG: close
    volumes:
      - backend:/app
    ports:
      - "3001:3001"
    restart: always
  postgres:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kpgts
    restart: always
volumes:
  frontend:
  backend:
  postgres:
    external: true